# Generated by Django 4.2.15 on 2026-07-11 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbits', '0001_initial'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('INACTIVE', 'Неактивна'), ('SEPARATED', 'Разделены'), ('COMPLETED', 'Работа завершена')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='Начало работы')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_pairs_female', to='rabbits.rabbit', verbose_name='Самка')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_pairs_male', to='rabbits.rabbit', verbose_name='Самец')),
            ],
            options={
                'verbose_name': 'Племенная пара',
                'verbose_name_plural': 'Племенные пары',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GenealogicalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название линии')),
                ('line_type', models.CharField(choices=[('MALE', 'Отцовская линия'), ('FEMALE', 'Материнское семейство')], max_length=10, verbose_name='Тип линии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('established_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата основания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='founded_lines', to='rabbits.rabbit', verbose_name='Основатель линии')),
            ],
            options={
                'verbose_name': 'Генеалогическая линия',
                'verbose_name_plural': 'Генеалогические линии',
                'ordering': ['line_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Kindling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindling_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окота')),
                ('litter_size', models.PositiveIntegerField(verbose_name='Количество в помете')),
                ('live_born', models.PositiveIntegerField(verbose_name='Живорожденных')),
                ('stillborn', models.PositiveIntegerField(default=0, verbose_name='Мертворожденных')),
                ('mummies', models.PositiveIntegerField(default=0, verbose_name='Мумифицированных')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.cage', verbose_name='Клетка')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kindlings', to='rabbits.rabbit', verbose_name='Самка')),
            ],
            options={
                'verbose_name': 'Окот',
                'verbose_name_plural': 'Окоты',
                'ordering': ['-kindling_date'],
            },
        ),
        migrations.CreateModel(
            name='KindlingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_order', models.PositiveIntegerField(verbose_name='Порядок рождения')),
                ('gender', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол')),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес при рождении (г)')),
                ('is_surviving', models.BooleanField(default=True, verbose_name='Выжил')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='breeding.kindling', verbose_name='Окот')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Крольчонок',
                'verbose_name_plural': 'Крольчата',
                'ordering': ['birth_order'],
            },
        ),
        migrations.CreateModel(
            name='RabbitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0, verbose_name='Поколение (0 = основатель)')),
                ('joined_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата включения')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='breeding.genealogicalline', verbose_name='Генеалогическая линия')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogical_lines', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Кролик в линии',
                'verbose_name_plural': 'Кролики в линиях',
                'unique_together': {('rabbit', 'line')},
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField(verbose_name='Дата спаривания')),
                ('expected_due_date', models.DateField(verbose_name='Ожидаемая дата окота')),
                ('actual_due_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окота')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('ultrasound_date', models.DateField(blank=True, null=True, verbose_name='Дата УЗИ')),
                ('embryos_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество эмбрионов')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='rabbits.rabbit', verbose_name='Самка')),
            ],
            options={
                'verbose_name': 'Беременность',
                'verbose_name_plural': 'Беременности',
                'ordering': ['-expected_due_date'],
                'indexes': [models.Index(fields=['female', '-expected_due_date'], name='breeding_pr_female__179bb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата спаривания')),
                ('method', models.CharField(choices=[('Natural', 'Естественное'), ('Artificial', 'Искусственное')], default='Natural', max_length=20, verbose_name='Метод')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matings', to='breeding.breedingpair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Спаривание',
                'verbose_name_plural': 'Спаривания',
                'ordering': ['-mating_date'],
                'indexes': [models.Index(fields=['pair', '-mating_date'], name='breeding_ma_pair_id_9d5fc3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kindling',
            index=models.Index(fields=['female', '-kindling_date'], name='breeding_ki_female__e49279_idx'),
        ),
        migrations.AddIndex(
            model_name='genealogicalline',
            index=models.Index(fields=['line_type', '-established_date'], name='breeding_ge_line_ty_6228cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='breedingpair',
            constraint=models.CheckConstraint(check=models.Q(('male', models.F('female')), _negated=True), name='male_female_different'),
        ),
    ]
