# Generated by Django 4.2.15 on 2026-07-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0002_alter_rabbit_status'),
        ('breeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancies_male', to='rabbits.rabbit', verbose_name='Самец-производитель'),
        ),
    ]
