# Generated by Django 4.2.15 on 2026-07-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbits', '0001_initial'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Группа крови')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергии')),
                ('chronic_illnesses', models.TextField(blank=True, verbose_name='Хронические заболевания')),
                ('last_vaccination', models.DateField(blank=True, null=True, verbose_name='Последняя прививка')),
                ('next_vaccination', models.DateField(blank=True, null=True, verbose_name='Следующая прививка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rabbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
            },
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Начало карантина')),
                ('end_date', models.DateField(verbose_name='Конец карантина')),
                ('reason', models.TextField(verbose_name='Причина карантина')),
                ('observations', models.TextField(blank=True, verbose_name='Наблюдения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.cage', verbose_name='Клетка карантина')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantines', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Карантин',
                'verbose_name_plural': 'Карантины',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['rabbit', '-start_date'], name='health_quar_rabbit__c9d8c7_idx'), models.Index(fields=['end_date'], name='health_quar_end_dat_6d326c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACCINATION', 'Прививка'), ('TREATMENT', 'Лечение'), ('QUARANTINE', 'Карантин'), ('CHECKUP', 'Осмотр'), ('SURGERY', 'Хирургия'), ('DEWORMING', 'Дегельминтизация'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип мероприятия')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('medication', models.CharField(blank=True, max_length=200, verbose_name='Лекарство')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Дозировка')),
                ('vet_name', models.CharField(blank=True, max_length=100, verbose_name='Ветеринар')),
                ('risk_level', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], default='LOW', max_length=10, verbose_name='Риск')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Ветеринарное мероприятие',
                'verbose_name_plural': 'Ветеринарные мероприятия',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['rabbit', '-date'], name='health_heal_rabbit__343546_idx'), models.Index(fields=['is_urgent', '-date'], name='health_heal_is_urge_039bad_idx')],
            },
        ),
    ]
