# Generated by Django 4.2.15 on 2026-07-11 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корм',
                'verbose_name_plural': 'Корма',
                'ordering': ['feed_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('HAY', 'Сено'), ('GRAIN', 'Зерно'), ('COMBINED', 'Комбикорм'), ('FRESH', 'Свежие корма'), ('SUPPLEMENT', 'Добавки'), ('OTHER', 'Другое')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('nutritional_value', models.JSONField(blank=True, null=True, verbose_name='Пищевая ценность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип корма',
                'verbose_name_plural': 'Типы кормов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (кг)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за кг')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('warehouse_location', models.CharField(blank=True, max_length=100, verbose_name='Место хранения')),
                ('last_replenished', models.DateField(default=django.utils.timezone.now, verbose_name='Последнее пополнение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='feeding.feed', verbose_name='Корм')),
            ],
            options={
                'verbose_name': 'Склад корма',
                'verbose_name_plural': 'Склады кормов',
                'ordering': ['-last_replenished'],
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeding.feedtype', verbose_name='Тип корма'),
        ),
        migrations.CreateModel(
            name='DailyFeedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общее количество (г)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'План кормления',
                'verbose_name_plural': 'Планы кормления',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (г)')),
                ('distribution_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата раздачи')),
                ('time_of_day', models.CharField(choices=[('MORNING', 'Утро'), ('AFTERNOON', 'День'), ('EVENING', 'Вечер')], default='MORNING', max_length=20, verbose_name='Время суток')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='feeding.feed', verbose_name='Корм')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_distributions', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Раздача корма',
                'verbose_name_plural': 'Раздачи кормов',
                'ordering': ['-distribution_date', '-time_of_day'],
                'indexes': [models.Index(fields=['rabbit', '-distribution_date'], name='feeding_fee_rabbit__1f4cc9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['expiry_date'], name='feeding_fee_expiry__6ddcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['batch_number'], name='feeding_fee_batch_n_130d76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfeedplan',
            unique_together={('date', 'rabbit')},
        ),
    ]
