# Generated by Django 4.2.15 on 2026-07-11 23:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество (кг)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за кг')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая стоимость')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата закупки')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер накладной')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='feeding.feed', verbose_name='Корм')),
            ],
            options={
                'verbose_name': 'Приход корма',
                'verbose_name_plural': 'Приходы кормов',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
