# Generated by Django 4.2.15 on 2026-07-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер ряда')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='housing.building', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер яруса')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='housing.row', verbose_name='Ряд')),
            ],
            options={
                'verbose_name': 'Ярус',
                'verbose_name_plural': 'Ярусы',
                'ordering': ['row', 'number'],
                'unique_together': {('row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер клетки')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость')),
                ('last_cleaned', models.DateField(blank=True, null=True, verbose_name='Последняя уборка')),
                ('last_disinfected', models.DateField(blank=True, null=True, verbose_name='Последняя дезинфекция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rabbit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cage', to='rabbits.rabbit', verbose_name='Текущий кролик')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='housing.shelf', verbose_name='Ярус')),
            ],
            options={
                'verbose_name': 'Клетка',
                'verbose_name_plural': 'Клетки',
                'ordering': ['shelf', 'number'],
                'unique_together': {('shelf', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount_ml', models.PositiveIntegerField(verbose_name='Количество (мл)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_consumptions', to='housing.cage', verbose_name='Клетка')),
            ],
            options={
                'verbose_name': 'Расход воды',
                'verbose_name_plural': 'Расход воды',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['cage', '-date'], name='housing_wat_cage_id_f69f94_idx')],
            },
        ),
        migrations.CreateModel(
            name='CageMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время перемещения')),
                ('moved_by', models.CharField(blank=True, max_length=100, verbose_name='Кто переместил')),
                ('reason', models.TextField(blank=True, verbose_name='Причина перемещения')),
                ('from_cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_from', to='housing.cage', verbose_name='Из клетки')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='rabbits.rabbit', verbose_name='Кролик')),
                ('to_cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_to', to='housing.cage', verbose_name='В клетку')),
            ],
            options={
                'verbose_name': 'Перемещение клетки',
                'verbose_name_plural': 'Перемещения клеток',
                'ordering': ['-moved_at'],
                'indexes': [models.Index(fields=['rabbit', '-moved_at'], name='housing_cag_rabbit__6d8c3a_idx')],
            },
        ),
    ]
