# Generated by Django 4.2.15 on 2026-07-11 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rabbit_id', models.CharField(max_length=20, unique=True, verbose_name='ID кролика')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Кличка')),
                ('gender', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('BREEDING', 'Племенной'), ('MEAT', 'Мясной'), ('PET', 'Декоративный'), ('DECEASED', 'Умер'), ('SOLD', 'Продан')], default='BREEDING', max_length=20, verbose_name='Статус')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='rabbits.rabbit', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='rabbits.rabbit', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Кролик',
                'verbose_name_plural': 'Кролики',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='RabbitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='rabbit_photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Фото кролика',
                'verbose_name_plural': 'Фото кроликов',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (г)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время взвешивания')),
                ('method', models.CharField(choices=[('manual', 'Ручной'), ('auto', 'Автоматический')], default='manual', max_length=20, verbose_name='Метод')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Веса',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['rabbit', '-measured_at'], name='rabbits_wei_rabbit__d1b780_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rabbit',
            index=models.Index(fields=['rabbit_id'], name='rabbits_rab_rabbit__25ae0a_idx'),
        ),
        migrations.AddIndex(
            model_name='rabbit',
            index=models.Index(fields=['birth_date'], name='rabbits_rab_birth_d_44c1fb_idx'),
        ),
    ]
