# Generated by Django 4.2.15 on 2026-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='status',
            field=models.CharField(choices=[('YOUNG', 'Молодняк'), ('BREEDING', 'Племенной'), ('MEAT', 'Мясной'), ('PET', 'Декоративный'), ('DECEASED', 'Умер'), ('SOLD', 'Продан')], default='BREEDING', max_length=20, verbose_name='Статус'),
        ),
    ]
