# Generated by Django 4.2.15 on 2026-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0002_alter_rabbit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='rabbit_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID кролика'),
        ),
    ]
