# Generated by Django 4.2.15 on 2026-07-13 22:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0003_alter_rabbit_rabbit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaughter_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата забоя')),
                ('live_weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Живой вес (г)')),
                ('carcass_weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Чистый вес тушки (г)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughters', to='rabbits.rabbit', verbose_name='Кролик')),
            ],
            options={
                'verbose_name': 'Забой',
                'verbose_name_plural': 'Забои',
                'ordering': ['-slaughter_date'],
                'indexes': [models.Index(fields=['-slaughter_date'], name='rabbits_sla_slaught_1deb7d_idx')],
            },
        ),
    ]
