# Generated by Django 4.2.15 on 2026-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('BREEDING', 'Разведение'), ('HEALTH', 'Здоровье'), ('FEEDING', 'Кормление'), ('PRODUCTION', 'Производство'), ('FINANCE', 'Финансы')], max_length=20, verbose_name='Тип отчета')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
                ('generated_by', models.CharField(max_length=100, verbose_name='Сгенерировал')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
